# This is a product release workflow that is manually triggered
name: Manual Production Release custom runner

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:          
 deploy:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@main
      - uses: jakejarvis/s3-sync-action@main
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git*/*'
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
